strategy_config <- list(
  initial_capital = 1000,
  holding_period = 10,
  data_start_date = "1995-01-01",
  backtest_start_date = "1999-01-01",
  leverage = 200,
  min_lot_pct = 0.02,
  max_lot_pct = 0.30,
  signal_symbol = "AUDUSD=X",
  filter_symbol = "GC=F",
  sma_period_range = seq(50, 150, by = 5),
  rsi_period_range = seq(10, 14, by = 2),
  rsi_oversold_range = seq(20, 30, by = 2),
  rsi_overbought_range = seq(70, 90, by = 2),
  filter_fast_range = seq(20, 50, by = 2),
  filter_slow_range = seq(60, 250, by = 5),
  use_kalman_options = c(TRUE, FALSE),
  chunk_size = 5000,
  num_cores = 24,
  output_root = "runs",
  resume_checkpoint = TRUE,
  garch_lookback = 500,
  garch_step = 1,
  garch_progress_every = 100,
  garch_trend_period = 5,
  min_training_rows = 20,
  # Money management
  kelly_fraction = 0.25,
  combine_lot_models = TRUE,
  # Phase 1 sampling: ~5.2M full grid -> ~50000 evaluated sets
  coarse_to_fine = TRUE,
  coarse_n_samples = 40000L,
  refine_top_k = 25L,
  refine_n_samples = 10000L,
  refine_window_steps = 3L,
  # Walk-forward CV
  walk_forward = TRUE,
  wf_n_folds = 5L,
  wf_embargo_bars = NULL,
  wf_min_train_rows = 30L
)
