strategy_config <- list(
  initial_capital = 1000,
  holding_period = 10,
  data_start_date = "2023-01-01",
  backtest_start_date = "2024-01-01",
  leverage = 200,
  min_lot_pct = 0.02,
  max_lot_pct = 0.30,
  signal_symbol = "EURUSD=X",
  filter_symbol = "GC=F",
  sma_period_range = c(50, 75),
  rsi_period_range = c(10, 14),
  rsi_oversold_range = c(24, 30),
  rsi_overbought_range = c(70, 80),
  filter_fast_range = c(20, 30),
  filter_slow_range = c(60, 90),
  use_kalman_options = c(FALSE),
  chunk_size = 50,
  num_cores = 1,
  output_root = "runs",
  resume_checkpoint = TRUE,
  garch_lookback = 120,
  garch_step = 20,
  garch_progress_every = 5,
  garch_trend_period = 3,
  min_training_rows = 20
)
